# Generated by Django 5.1.6 on 2025-03-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='invite_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
