# Generated by Django 5.1.6 on 2025-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
