# Generated by Django 5.1.6 on 2025-03-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_board_invite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='invite_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
